name: example
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  simple_html_css:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  uses-material-design: true
