name: simple_html_css
description: This package allows you to use simple HTML and inline CSS styles to style your text in flutter. A fork of css_text package.
version: 2.0.1
homepage: https://github.com/ali-thowfeek/simple_html_css_flutter
repository: https://github.com/ali-thowfeek/simple_html_css_flutter
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^4.5.1
  html_unescape: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
